services:
  my-node-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "my-node-app"
    ports:
      - "3000:3000"
    # environment: 
    #   - NODE_ENV=production
    restart: unless-stopped
