services:
  spotify-card-mapping:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "spotify-card-mapping"
    volumes: 
      - data:/usr/src/app/data
    ports:
      - "3000:3000"
    # environment: 
    #   - NODE_ENV=production
    restart: unless-stopped
volumes:
  data: